#!/usr/bin/env python3
"""One-time migration: create domain-only GeoJSON files from existing per-variable ones.

Run this once to create D01.geojson, D02.geojson, etc. from the existing
D01_TEMP.geojson, D02_TEMP.geojson, etc. After the next pipeline run,
the new format will be generated automatically.

Usage:
    python migrate_geojson.py [--geojson-dir site/geoJSON]
"""

import json
import shutil
import sys
from pathlib import Path


def migrate(geojson_dir: str = "site/geoJSON") -> None:
    gdir = Path(geojson_dir)
    if not gdir.exists():
        print(f"Directory not found: {gdir}")
        sys.exit(1)

    domains = ["D01", "D02", "D03", "D04"]

    for domain in domains:
        target = gdir / f"{domain}.geojson"
        if target.exists():
            print(f"  OK {target.name} already exists -- skipping")
            continue

        # Find any existing per-variable GeoJSON for this domain
        source = None
        for f in sorted(gdir.glob(f"{domain}_*.geojson")):
            source = f
            break

        if source is None:
            print(f"  SKIP No source found for {domain} -- skipping")
            continue

        # Read, strip colormap from metadata, and write compact
        with open(source, "r", encoding="utf-8") as fh:
            data = json.load(fh)

        # Remove colormap from metadata (frontend reads from VARIABLES_CONFIG)
        if "metadata" in data and "colormap" in data["metadata"]:
            del data["metadata"]["colormap"]

        with open(target, "w", encoding="utf-8") as fh:
            json.dump(data, fh, separators=(",", ":"), ensure_ascii=False)

        src_size = source.stat().st_size
        dst_size = target.stat().st_size
        savings = (1 - dst_size / src_size) * 100 if src_size > 0 else 0

        print(f"  OK {source.name} -> {target.name} ({src_size:,} -> {dst_size:,} bytes, {savings:.0f}% smaller)")

    print("\nDone! Old per-variable GeoJSON files can be removed after verification.")
    print("They will NOT be regenerated by the updated pipeline.")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Migrate GeoJSON to domain-only format")
    parser.add_argument("--geojson-dir", default="site/geoJSON", help="Path to geoJSON directory")
    args = parser.parse_args()
    migrate(args.geojson_dir)
